name: firenoteapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  firebase_database: ^9.0.8
  flutter_slidable: ^1.2.0
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+10
  cached_network_image: ^3.2.0
  lottie: ^1.2.2
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/translations/

