Map <String, String> enEN = {
  "email": "Email",
  "password": "Password",
  "lastname": "Lastname",
  "firstname": "Firstname",
  "phone": "Phone",
  "sign_in": "Sign in",
  "not_account": "Do not have an account?",
  "sign_up": "Sign up",
  "have_account": "Do have an account?",
  "title": "Title",
  "content": "Content",
  "add": "Add",
  "add_user": "Add user",
  "detail_note": "Detail of Note",
  "edit": "Edit",
  "delete": "Delete",
  "delete_user": "Delete user",
  "home": "Home",
  "log_out": "Log out",
  "menu": "Menu",
  "user_settings": "User's settings",
  "change_mode": "Change Mode",
  "change_lang": "Change language",
  "source": "Is Gallery:"
};